### ISSUE TITLE
Module Not Working in Node.js

### ISSUE THREAD

**Issue by neurolag** [p-toy-factory/ts-nameof-proxy#1]
I just tried to migrate from `ts-nameof` to this module.
However, I had to notice that this module does not work using Node.js.

Looks like Webpack is messing things up somehow...?
I get the following error:

```
ReferenceError: self is not defined
    at Object.<anonymous> (./node_modules/ts-nameof-proxy/dist/ts-nameof-proxy.js:3:3)
```

That said, the variable `self` is only defined in web browsers.

**Comment by PinkChampagne17** [comment]
I'm sorry I only recently solved this problem, thank you very much for your feedback which was instrumental in helping me improve this package.

**Comment by neurolag** [comment]
You're most welcome! Thanks for taking care 😄
